# Generated by Django 4.2.5 on 2023-09-12 04:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='choice',
            old_name='questionb',
            new_name='question',
        ),
    ]
